samples:                           "samples.csv"
methods:                           ["blastn","centrifuge","idtaxa","kraken","megablast","minimap","mothur","qiime","rdp","spingo"]

porechop:
    environment:                   "../envs/preprocess.yml"
    threads:                       16
    memory:                        4000
    checkreads:                    20000 

nanofilt:
    environment:                   "../envs/preprocess.yml"
    memory:                        2000
    minlen:                        1400
    maxlen:                        1600
    quality:                       10

subsample:
    skip:                          false
    samplesize:                    100
    environment:                   "../envs/preprocess.yml"

nanostats:
    environment:                   "../envs/preprocess.yml"
    threads:                       2
    memory:                        8000

nanoplot:
    environment:                   "../envs/preprocess.yml"
    memory:                        4000
    downsample:                    0

common:
    environment:                   "../envs/R4.0.yml"
    dburl:                         "https://www.arb-silva.de/fileadmin/silva_databases/qiime/Silva_132_release.zip"
    ssu:                           "16S" #16S or 18S
    dbmemory:                      4000
    group-by:                      sample

blastn:
    environment:                   "../envs/blast.yml"
    threads:                       10
    memory:                        500

centrifuge:
    environment:                   "../envs/centrifuge.yml"
    taxmapurl:                     "https://www.arb-silva.de/fileadmin/silva_databases/release_132/Exports/taxonomy/taxmap_embl_ssu_ref_nr99_132.txt.gz"
    sequrl:                        "https://www.arb-silva.de/fileadmin/silva_databases/release_132/Exports/SILVA_132_SSURef_Nr99_tax_silva.fasta.gz"
    dbthreads:                     4
    dbmemory:                      500
    threads:                       1
    memory:                        16000

idtaxa:
    environment:                   "../envs/R4.0.yml"
    dbmemory:                      3000
    threads:                       8
    memory:                        10000

kraken:
    environment:                   "../envs/kraken2.yml"
    dbtype:                        "silva"
    dbthreads:                     8
    dbmemory:                      1000
    threads:                       16
    memory:                        500

mapseq:
    threads:                       1
    memory:                        1000

megablast:
    environment:                   "../envs/blast.yml"
    threads:                       10
    memory:                        500

minimap:
    environment:                   "../envs/minimap2.yml"
    dbmemory:                      3000
    threads:                       16
    memory:                        50000

mothur:
    environment:                   "../envs/mothur.yml"
    dbmemory:                      1000
    threads:                       8
    memory:                        20000

qiime:
    environment:                   "../envs/qiime2.yml"
    dbmemory:                      3000
    threads:                       16
    memory:                        10000

rdp:
    environment:                   "../envs/R4.0.yml"
    dbmemory:                      75000
    threads:                       8
    memory:                        5000

spingo:
    environment:                   "../envs/spingo.yml"
    dbthreads:                     16
    dbmemory:                      50000
    threads:                       16
    memory:                        50000
